title: Home of the Cliveome
author: Clive G Brown
email: support@nanoporetech.com
description: > # this means to ignore newlines until "baseurl:"
  A self-sequencing project
#baseurl: ""
twitter_username: clive_g_brown
github_username:  clive-g-brown

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
